/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.ReservationMenu.ReturnDate;
//import static GUI.ReservationMenu.validateRoom;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ll_project_programmed_jeisonsaborio_gabrielperez.GlobalVariables;

/**
 *
 * @author Gabriel
 */
public final class Consult8 extends javax.swing.JFrame {
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    DateFormat dateFormat = DateFormat.getDateInstance();
    DefaultTableModel tableRoomAvailable;
    String data1[][] = {};
    String cabeza1[] = {"Price","Type room","Room number","Maximum People"};
    public Consult8() {
        initComponents();
        tableRoomAvailable = new DefaultTableModel(data1,cabeza1);
        TabRoomAvailable.setModel(tableRoomAvailable);
        loadHotel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void loadHotel(){
        CobListHotel.removeAllItems(); 
        for (int i = 0; i < GlobalVariables.getInstance().hotelList.size(); i++) {
            CobListHotel.addItem(GlobalVariables.getInstance().hotelList.get(i).getName());
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CobListHotel = new javax.swing.JComboBox();
        BtoSeach = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabRoomAvailable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        DateCheckIn = new com.toedter.calendar.JDateChooser();
        DateCheckOut = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Rooms available:");

        BtoSeach.setText("Seach");
        BtoSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtoSeachActionPerformed(evt);
            }
        });

        TabRoomAvailable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabRoomAvailable);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Check-In:");

        jLabel3.setText("Check-Out:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(DateCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(DateCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(CobListHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtoSeach, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(DateCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DateCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CobListHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtoSeach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtoSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtoSeachActionPerformed
        // TODO add your handling code here:
      
        for(int x = 0; x < TabRoomAvailable.getRowCount(); x++){
            tableRoomAvailable.removeRow(x);
            x -= 1;
        }
        
        try{
            GlobalVariables.getInstance().entryDate =  dateFormat.format(DateCheckIn.getDate());
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Select entryDate ");
            return;
        }
        
        try{
            GlobalVariables.getInstance().departureDate = dateFormat.format(DateCheckOut.getDate()); 
           
        }catch(Exception e){
           JOptionPane.showMessageDialog(this,"Select departureDate ");
           return;
        }
        String hotel = CobListHotel.getSelectedItem().toString();
        for(int j = 0; j < GlobalVariables.getInstance().hotelList.size();j++){
            if(GlobalVariables.getInstance().hotelList.get(j).getName().equals(hotel)){
                GlobalVariables.getInstance().hotel = GlobalVariables.getInstance().hotelList.get(j);
                for(int i = 0; i<GlobalVariables.getInstance().hotelList.get(j).getRoomsList().size();i++){
                    boolean busy = false;
                    for(int x = 0;x<GlobalVariables.getInstance().hotelList.get(j).getReservationList().size();x++){ 
                        for(int h=0;h<GlobalVariables.getInstance().hotelList.get(j).getReservationList().get(x).getRoomsList().size();h++){       
                            if(GlobalVariables.getInstance().hotelList.get(j).getRoomsList().get(i).getRoomNumber() == GlobalVariables.getInstance().hotelList.get(j).getReservationList().get(x).getRoomsList().get(h).getRoomNumber()){
                                try {
                                    Date fechaDate1 = formato.parse(GlobalVariables.getInstance().hotel.getReservationList().get(x).getEntryDate());
                                    Date fechaDate2 = formato.parse(GlobalVariables.getInstance().hotel.getReservationList().get(x).getDepartureDate());
                                    Date fechaDate3 = formato.parse(ReturnDate());
                                    if ((fechaDate1.after(fechaDate3)) &&(fechaDate2.after(fechaDate3))){
                                        boolean response1 = ReservationMenu.validateRoom(x);
                                        if(response1 == true){
                                            busy = true;
                                        }
                                    }
                                } catch (ParseException ex) {
                                    Logger.getLogger(ReservationMenu.class.getName()).log(Level.SEVERE, null, ex);
                                }
                          
                            }   
                        
                           
                                              
                        }      
                    }
                    if(busy == false){
                        Object datos[] = {GlobalVariables.getInstance().hotelList.get(j).getRoomsList().get(i).getPrice(),
                        GlobalVariables.getInstance().hotelList.get(j).getRoomsList().get(i).getTypeRoom().getName(),
                        GlobalVariables.getInstance().hotelList.get(j).getRoomsList().get(i).getRoomNumber(),
                        GlobalVariables.getInstance().hotelList.get(j).getRoomsList().get(i).getTypeRoom().getMaximumPeople()};
                        tableRoomAvailable.addRow(datos);

                    }

                }
                        
            }
        }
    }//GEN-LAST:event_BtoSeachActionPerformed
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CustomerMain customerMain = new CustomerMain();
        customerMain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consult8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consult8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consult8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consult8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consult8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtoSeach;
    private javax.swing.JComboBox CobListHotel;
    private com.toedter.calendar.JDateChooser DateCheckIn;
    private com.toedter.calendar.JDateChooser DateCheckOut;
    private javax.swing.JTable TabRoomAvailable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
