/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ll_project_programmed_jeisonsaborio_gabrielperez.GlobalVariables;

/**
 *
 * @author Jeison
 */
public final class HotelMenu extends javax.swing.JFrame {
    DefaultListModel model1 = new DefaultListModel();
    DefaultListModel model2 = new DefaultListModel();
    DefaultTableModel tableRoom;
    String data2[][] = {};
    String cabeza2[] = {"Room Number","Type Room","Maximum People","Size","Description","Terrace","SeaView","Everything Included","Smoke"};
    /**
     * Creates new form ReservationsMenu
     */
    public HotelMenu() {
        initComponents();
        tableRoom = new DefaultTableModel(data2,cabeza2);
        TabRoom.setModel(tableRoom);
        showHotel();
    }

    public void showHotel(){
        String controlE;
        String controlT;
        String controlV;
        String controlS;
        LabName.setText(GlobalVariables.getInstance().hotel.getName());
        LabCountry.setText(GlobalVariables.getInstance().hotel.getCountry());
        LabAddress.setText(GlobalVariables.getInstance().hotel.getAddress());
        LabPhoneNumber.setText(Integer.toString(GlobalVariables.getInstance().hotel.getPhoneNumber()));
        LabStars.setText(Integer.toString(GlobalVariables.getInstance().hotel.getNumberStars()));
        LabAccommodationType.setText(GlobalVariables.getInstance().hotel.getAccommodationType());
        LabSize.setText(Integer.toString(GlobalVariables.getInstance().hotel.getSize()));
        LabCheckIn.setText(GlobalVariables.getInstance().hotel.getHourCheckIn());
        LabcheckinRequirements.setText(GlobalVariables.getInstance().hotel.getRequirementsCheckIn());
        LabCheckOut.setText(GlobalVariables.getInstance().hotel.getHourCheckOut());
        
    
        for(int i = 0; i<GlobalVariables.getInstance().hotel.getServiceList().size();i++){        
            model1.addElement(GlobalVariables.getInstance().hotel.getServiceList().get(i).getName());
                    
        }
        ListServices.setModel(model1);
        
        
        for(int y = 0; y<GlobalVariables.getInstance().hotel.getAttractionList().size();y++){        
            model2.addElement(GlobalVariables.getInstance().hotel.getAttractionList().get(y).getName());
                    
        }
        ListServices.setModel(model2);
        
        for(int x =0; x < GlobalVariables.getInstance().hotel.getRoomsList().size();x++){
            if(GlobalVariables.getInstance().hotel.getRoomsList().get(x).getTypeRoom().isEverythingIncluded() == true){
                controlE = "";               
            }else{
                controlE = "";
            }
            if(GlobalVariables.getInstance().hotel.getRoomsList().get(x).getTypeRoom().isTerrace() == true){
                controlT = "";
            }else{
                controlT = "";
            }
            if(GlobalVariables.getInstance().hotel.getRoomsList().get(x).getTypeRoom().isSmoke() == true){
                controlS = "";
            }else{
                controlS = "";
            }
            if(GlobalVariables.getInstance().hotel.getRoomsList().get(x).getTypeRoom().isView() == true){
                controlV = "";
            }else{
                controlV = "";
            }
            Object datos[] = {GlobalVariables.getInstance().hotel.getRoomsList().get(x).getRoomNumber(),
                    GlobalVariables.getInstance().hotel.getRoomsList().get(x).getTypeRoom().getName(),
                    GlobalVariables.getInstance().hotel.getRoomsList().get(x).getTypeRoom().getMaximumPeople(),
                    GlobalVariables.getInstance().hotel.getRoomsList().get(x).getTypeRoom().getDescription(),
                    GlobalVariables.getInstance().hotel.getRoomsList().get(x).getTypeRoom().getSize(),
                    controlT,controlS,controlE,controlV};
                tableRoom.addRow(datos);
            
        }
        
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LabCountry = new javax.swing.JLabel();
        LabAddress = new javax.swing.JLabel();
        LabName = new javax.swing.JLabel();
        LabPhoneNumber = new javax.swing.JLabel();
        LabStars = new javax.swing.JLabel();
        LabAccommodationType = new javax.swing.JLabel();
        LabSize = new javax.swing.JLabel();
        LabCheckIn = new javax.swing.JLabel();
        LabCheckOut = new javax.swing.JLabel();
        LabcheckinRequirements = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListServices = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabRoom = new javax.swing.JTable();
        BtoBack = new javax.swing.JButton();
        BtoReservation = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabCountry.setText("jLabel2");

        LabAddress.setText("jLabel2");

        LabName.setText("jLabel1");

        LabPhoneNumber.setText("jLabel1");

        LabStars.setText("jLabel2");

        LabAccommodationType.setText("jLabel2");

        LabSize.setText("jLabel2");

        LabCheckIn.setText("jLabel2");

        LabCheckOut.setText("jLabel2");

        LabcheckinRequirements.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabStars, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabSize, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabAccommodationType, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                .addGap(17, 17, 17))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabName, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(LabAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(LabcheckinRequirements, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabName)
                    .addComponent(LabCountry))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabPhoneNumber)
                    .addComponent(LabAddress))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(LabStars))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(LabAccommodationType)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabSize)
                    .addComponent(LabCheckIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(LabCheckOut)
                .addGap(4, 4, 4)
                .addComponent(LabcheckinRequirements)
                .addGap(28, 28, 28))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setViewportView(ListServices);

        jLabel2.setText("Services");

        jLabel3.setText("Attractions");

        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Choose room:");

        TabRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TabRoom);

        BtoBack.setText("Back");
        BtoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtoBackActionPerformed(evt);
            }
        });

        BtoReservation.setText("Reservation");
        BtoReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtoReservationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(BtoBack)
                .addGap(146, 146, 146)
                .addComponent(BtoReservation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtoBack)
                    .addComponent(BtoReservation))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtoReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtoReservationActionPerformed
        // TODO add your handling code here:
        int row;
       
        row = TabRoom.getSelectedRow();
        
        if(row == -1){
            JOptionPane.showMessageDialog(this,"Selections hotel");
        }else{
            GlobalVariables.getInstance().typeRoom = TabRoom.getValueAt(row, 1).toString();
            if(GlobalVariables.getInstance().person == null){
                LogInmMenu logInMenu = new LogInmMenu();
                logInMenu.setVisible(true);   
                this.dispose();
                
            }else{
                ReservationMenu reservationMenu = new ReservationMenu();
                reservationMenu.setVisible(true);
                this.dispose();
                
            }
            
           
        }    
    }//GEN-LAST:event_BtoReservationActionPerformed

    private void BtoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtoBackActionPerformed
        // TODO add your handling code here:
        SearchResultsMenu searchResultsMenu = new SearchResultsMenu();
        searchResultsMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtoBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtoBack;
    private javax.swing.JButton BtoReservation;
    private javax.swing.JLabel LabAccommodationType;
    private javax.swing.JLabel LabAddress;
    private javax.swing.JLabel LabCheckIn;
    private javax.swing.JLabel LabCheckOut;
    private javax.swing.JLabel LabCountry;
    private javax.swing.JLabel LabName;
    private javax.swing.JLabel LabPhoneNumber;
    private javax.swing.JLabel LabSize;
    private javax.swing.JLabel LabStars;
    private javax.swing.JLabel LabcheckinRequirements;
    private javax.swing.JList ListServices;
    private javax.swing.JTable TabRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
