/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import ll_project_programmed_jeisonsaborio_gabrielperez.GlobalVariables;
import org.apache.commons.codec.digest.DigestUtils;


/**
 *
 * @author Jeison
 */
public class LogInmMenu extends javax.swing.JFrame {

    /**
     * Creates new form LogInmMenu
     */
    public LogInmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TxtEmailAddress = new javax.swing.JTextField();
        BtoLogIn = new javax.swing.JButton();
        BtoSignUp = new javax.swing.JButton();
        TxtPPassWord = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel14.setText("Password:");

        jLabel13.setText("Email address:");

        TxtEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmailAddressActionPerformed(evt);
            }
        });

        BtoLogIn.setText("Log in");
        BtoLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtoLogInActionPerformed(evt);
            }
        });

        BtoSignUp.setText("Sign Up");
        BtoSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtoSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtPPassWord)
                    .addComponent(TxtEmailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(BtoLogIn)
                .addGap(66, 66, 66)
                .addComponent(BtoSignUp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TxtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TxtPPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtoLogIn)
                    .addComponent(BtoSignUp))
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmailAddressActionPerformed

    private void BtoSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtoSignUpActionPerformed
        // TODO add your handling code here:
        RegisterMenu registerMenu = new RegisterMenu();
        registerMenu.setVisible(true);
    }//GEN-LAST:event_BtoSignUpActionPerformed

    private void BtoLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtoLogInActionPerformed
        // TODO add your handling code here:
        String email = TxtEmailAddress.getText();
        String passWord = new String (TxtPPassWord.getPassword());
        passWord = DigestUtils.md5Hex(passWord);
        System.out.println(passWord);
        for(int i = 0; i < GlobalVariables.getInstance().peopleList.size();i++){
            if(GlobalVariables.getInstance().peopleList.get(i).getEmailAddress().equals(email)){
                if(GlobalVariables.getInstance().peopleList.get(i).getPassWord().equals(passWord)){
                    if(GlobalVariables.getInstance().peopleList.get(i).getType().equals("Customer")){
                        CustomerMain customerMain = new CustomerMain();
                        customerMain.setVisible(true);
                    }else if(GlobalVariables.getInstance().peopleList.get(i).getType().equals("Staff")){
                        StaffMain staffMain = new StaffMain();
                        staffMain.setVisible(true);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this,"Email or password incorrect");
                }
            }
        }
    }//GEN-LAST:event_BtoLogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtoLogIn;
    private javax.swing.JButton BtoSignUp;
    private javax.swing.JTextField TxtEmailAddress;
    private javax.swing.JPasswordField TxtPPassWord;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    // End of variables declaration//GEN-END:variables
}
