/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ll_project_programmed_jeisonsaborio_gabrielperez.Attraction;
import ll_project_programmed_jeisonsaborio_gabrielperez.GlobalVariables;
import ll_project_programmed_jeisonsaborio_gabrielperez.Hotel;

/**
 *
 * @author Jeison
 */
public class SearchResultsMenu extends javax.swing.JFrame {
    DefaultTableModel tableSearchHotels;
    String data1[][] = {};
    String cabeza1[] = {"Name","Address","Country","PhoneNumber","Accommodation type","Hour Check-In","Hour Check-Out"};
   
    public SearchResultsMenu() {
        initComponents();
        tableSearchHotels = new DefaultTableModel(data1,cabeza1);
        TabSearchHotels.setModel(tableSearchHotels);
    }
    
    public void loardHotel(String description){
        for(int i =0; i < GlobalVariables.getInstance().hotelList.size();i++){
            if((GlobalVariables.getInstance().hotelList.get(i).getAddress().equals(description))||(GlobalVariables.getInstance().hotelList.get(i).getName().equals(description))){
                Object datos[] = {GlobalVariables.getInstance().hotelList.get(i).getName(),
                    GlobalVariables.getInstance().hotelList.get(i).getAddress(),
                    GlobalVariables.getInstance().hotelList.get(i).getCountry(),
                    GlobalVariables.getInstance().hotelList.get(i).getPhoneNumber(),
                    GlobalVariables.getInstance().hotelList.get(i).getAccommodationType(),
                    GlobalVariables.getInstance().hotelList.get(i).getHourCheckIn(),
                    GlobalVariables.getInstance().hotelList.get(i).getHourCheckOut()};
                tableSearchHotels.addRow(datos);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtoSortPrice = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabSearchHotels = new javax.swing.JTable();
        BtoBack = new javax.swing.JButton();
        BtoContinue = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Search Results:");

        BtoSortPrice.setText("Sort price");
        BtoSortPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtoSortPriceActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stars(high to low)", "Stars(low to high)" }));

        jLabel2.setText("Start rating");

        jLabel3.setText("Accommodation type");

        TabSearchHotels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabSearchHotels);

        BtoBack.setText("Back");

        BtoContinue.setText("Continue");
        BtoContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtoContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtoSortPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(BtoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(BtoContinue)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtoSortPrice))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtoBack)
                    .addComponent(BtoContinue))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtoContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtoContinueActionPerformed
        // TODO add your handling code here:
        int row;
       
        row = TabSearchHotels.getSelectedRow();
        
        if(row == -1){
            JOptionPane.showMessageDialog(this,"Selections hotel");
        }else{
            String nameHotel = TabSearchHotels.getValueAt(row, 0).toString();
            for(int i = 0; i < GlobalVariables.getInstance().hotelList.size();i++){
                if(nameHotel.equals(GlobalVariables.getInstance().hotelList.get(i).getName())){
                    GlobalVariables.getInstance().hotel = GlobalVariables.getInstance().hotelList.get(i);
                    HotelMenu hotelMenu = new HotelMenu();
                    hotelMenu.setVisible(true);
                    
                }
            }
        }
    }//GEN-LAST:event_BtoContinueActionPerformed

    private void BtoSortPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtoSortPriceActionPerformed

            String []fila= new String[7];
            String[]titulos = {"Name","Address","Country","PhoneNumber","Accommodation type","Hour Check-In","Hour Check-Out"};
            TabSearchHotels.repaint();
            DefaultTableModel model = new DefaultTableModel(null, titulos);
            TabSearchHotels.setModel(model);
            
            
        ArrayList<Hotel> hotels = GlobalVariables.getInstance().getAll();
        
        int cont = hotels.size();
        while(cont !=0){
             for (int i = 0; i < hotels.size(); i++) {
                
            }
        }
            
            
                //fila[0]=a;
                //fila[1]=b;
                //fila[2]=c;
                //fila[3]=d;
                //fila[3]=d;
                //fila[3]=d;
                //fila[3]=d;    

            

                model.addRow(fila);         
                TabSearchHotels.setModel(model);
                
        
        
    }//GEN-LAST:event_BtoSortPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchResultsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchResultsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchResultsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchResultsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchResultsMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtoBack;
    private javax.swing.JButton BtoContinue;
    private javax.swing.JButton BtoSortPrice;
    private javax.swing.JTable TabSearchHotels;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
