/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import ll_project_programmed_jeisonsaborio_gabrielperez.Attraction;
import ll_project_programmed_jeisonsaborio_gabrielperez.GlobalVariables;
import ll_project_programmed_jeisonsaborio_gabrielperez.Hotel;
import ll_project_programmed_jeisonsaborio_gabrielperez.Room;
import ll_project_programmed_jeisonsaborio_gabrielperez.Season;
import ll_project_programmed_jeisonsaborio_gabrielperez.Service;
import ll_project_programmed_jeisonsaborio_gabrielperez.TypeRoom;

/**
 *
 * @author Jeison
 */
public final class StaffMain extends javax.swing.JFrame {

    String originalName;
    public StaffMain() {
        initComponents();
    
        setHotels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel50 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        TextHotelNameManage = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TextHotelAddressManage = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TextHotelCountryManage = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TextHotelPhoneNumberManage = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TextHotelYearOfBuildingManage = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ComboBoxHotelKindOfLodgingManage = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        TextHotelSizeManage = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextPaneHotelRequirementsForCheckInManage = new javax.swing.JTextPane();
        jLabel23 = new javax.swing.JLabel();
        ComboBoxHotelStarsManage = new javax.swing.JComboBox();
        ComboBoxHotelHourOfCheckInManage = new javax.swing.JComboBox();
        ComboBoxHotelHourOfCheckOutManage = new javax.swing.JComboBox();
        ButtonExitManage = new javax.swing.JButton();
        ButtonSaveManage = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ButtonDelete = new javax.swing.JButton();
        ComboBoxListHotels1 = new javax.swing.JComboBox();
        ButtonLoadData = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ComboBoxListHotels = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        ButtonSaveRoom = new javax.swing.JButton();
        ButtonSaveAttractio = new javax.swing.JButton();
        ButtonSaveService = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        TextRoomNumber = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        ComboBoxKindOfRoom = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        TextMaxOfPeople = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        TextSize = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextPaneDescription = new javax.swing.JTextPane();
        RadioButtonAllInclude = new javax.swing.JRadioButton();
        RadioButtonTerrace = new javax.swing.JRadioButton();
        RadioButtonSeaView = new javax.swing.JRadioButton();
        RadioButtonSmoke = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        TextCodeAttraction = new javax.swing.JTextField();
        TextNameAttraction = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        TextCodeService = new javax.swing.JTextField();
        TextNameService = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        ComboBoxSeasons = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        ComboBoxRooms = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        TextFieldPriceOfRoom = new javax.swing.JTextField();
        ButtonSaveSeason = new javax.swing.JButton();
        DateChooserStartDate = new com.toedter.calendar.JDateChooser();
        DateChooserDepartureDate = new com.toedter.calendar.JDateChooser();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        ButtonExitManage1 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TextHotelName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextHotelAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextHotelCountry = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextHotelPhoneNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextHotelYearOfBuilding = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ComboBoxHotelKindOfLodging = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        TextHotelSize = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextPaneHotelRequirementsForCheckIn = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        ComboBoxHotelStars = new javax.swing.JComboBox();
        ComboBoxHotelHourOfCheckIn = new javax.swing.JComboBox();
        ComboBoxHotelHourOfCheckOut = new javax.swing.JComboBox();
        ButtonCreateHotel = new javax.swing.JButton();
        ButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel12.setText("Select a hotel");

        jLabel13.setText("Hotel name");

        jLabel14.setText("Address ");

        jLabel15.setText("Country");

        jLabel16.setText("Phone number");

        jLabel17.setText("Year of building");

        jLabel18.setText("kind of lodging");

        ComboBoxHotelKindOfLodgingManage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mountain", "Beach", "City" }));

        jLabel19.setText("Size");

        jLabel20.setText("Hour of Check in");

        jLabel21.setText("Hour of Check out");

        jLabel22.setText("Requirements for check in");

        jScrollPane2.setViewportView(TextPaneHotelRequirementsForCheckInManage);

        jLabel23.setText("Stars");

        ComboBoxHotelStarsManage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        ComboBoxHotelHourOfCheckInManage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7 am", "8 am", "9 am" }));

        ComboBoxHotelHourOfCheckOutManage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7 pm", "8 pm", "9 pm" }));

        ButtonExitManage.setText("Exit");
        ButtonExitManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExitManageActionPerformed(evt);
            }
        });

        ButtonSaveManage.setText("Save");
        ButtonSaveManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveManageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel50Layout = new javax.swing.GroupLayout(jPanel50);
        jPanel50.setLayout(jPanel50Layout);
        jPanel50Layout.setHorizontalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel50Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel13))
                .addGap(39, 39, 39)
                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextHotelNameManage, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel50Layout.createSequentialGroup()
                        .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextHotelAddressManage, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                .addComponent(TextHotelCountryManage)
                                .addComponent(TextHotelPhoneNumberManage)
                                .addComponent(TextHotelYearOfBuildingManage))
                            .addComponent(TextHotelSizeManage, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonExitManage))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel50Layout.createSequentialGroup()
                                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel18))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ComboBoxHotelKindOfLodgingManage, javax.swing.GroupLayout.Alignment.LEADING, 0, 224, Short.MAX_VALUE)
                                    .addComponent(ComboBoxHotelStarsManage, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboBoxHotelHourOfCheckOutManage, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboBoxHotelHourOfCheckInManage, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel50Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel50Layout.createSequentialGroup()
                                        .addGap(0, 152, Short.MAX_VALUE)
                                        .addComponent(ButtonSaveManage)
                                        .addGap(13, 13, 13)))))))
                .addGap(0, 69, Short.MAX_VALUE))
        );
        jPanel50Layout.setVerticalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel50Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TextHotelNameManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(ComboBoxHotelHourOfCheckInManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextHotelAddressManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel21)
                    .addComponent(ComboBoxHotelHourOfCheckOutManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextHotelCountryManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(ComboBoxHotelKindOfLodgingManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel50Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextHotelPhoneNumberManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel50Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(ComboBoxHotelStarsManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel50Layout.createSequentialGroup()
                        .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(TextHotelYearOfBuildingManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(TextHotelSizeManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSaveManage)
                    .addComponent(ButtonExitManage)))
        );

        ButtonDelete.setText("Delete Hotel");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        ButtonLoadData.setText("Load data");
        ButtonLoadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoadDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxListHotels1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonLoadData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonDelete)
                        .addGap(83, 83, 83))))
            .addComponent(jSeparator1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ButtonDelete)
                    .addComponent(ComboBoxListHotels1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonLoadData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Edit or delete a hotel", jPanel2);

        jPanel3.setFocusable(false);

        jLabel25.setText("Select a hotel");

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        ButtonSaveRoom.setText("Save");
        ButtonSaveRoom.setEnabled(false);
        ButtonSaveRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveRoomActionPerformed(evt);
            }
        });

        ButtonSaveAttractio.setText("Save");
        ButtonSaveAttractio.setEnabled(false);
        ButtonSaveAttractio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveAttractioActionPerformed(evt);
            }
        });

        ButtonSaveService.setText("Save");
        ButtonSaveService.setEnabled(false);
        ButtonSaveService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveServiceActionPerformed(evt);
            }
        });

        jLabel32.setText("Room number");

        TextRoomNumber.setEnabled(false);

        jLabel33.setText("Kind of room");

        ComboBoxKindOfRoom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Suit", "Double", "Individual" }));
        ComboBoxKindOfRoom.setEnabled(false);

        jLabel34.setText("Max of people");

        TextMaxOfPeople.setEnabled(false);

        jLabel35.setText("Size");

        TextSize.setEnabled(false);

        jLabel36.setText("Description");

        TextPaneDescription.setEnabled(false);
        jScrollPane3.setViewportView(TextPaneDescription);

        RadioButtonAllInclude.setText("AllI included");
        RadioButtonAllInclude.setEnabled(false);
        RadioButtonAllInclude.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RadioButtonAllIncludeMouseClicked(evt);
            }
        });

        RadioButtonTerrace.setText("Terrace");
        RadioButtonTerrace.setEnabled(false);

        RadioButtonSeaView.setText("Sea view");
        RadioButtonSeaView.setEnabled(false);

        RadioButtonSmoke.setText("Smoke");
        RadioButtonSmoke.setEnabled(false);

        jButton4.setText("Add Attraction");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Add Services");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel24.setText("Code");

        jLabel26.setText("Name");

        TextCodeAttraction.setEnabled(false);

        TextNameAttraction.setEnabled(false);

        jLabel27.setText("Code");

        jLabel28.setText("Name");

        TextCodeService.setEnabled(false);

        TextNameService.setEnabled(false);

        jButton3.setText("Add Room");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        ComboBoxSeasons.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "High season (+25%)", "Low season (normal)", "Green season (-50%)" }));
        ComboBoxSeasons.setEnabled(false);

        jButton1.setText("Add seasons");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ComboBoxRooms.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Suit", "Double", "Individual" }));
        ComboBoxRooms.setEnabled(false);

        jLabel29.setText("Price $");

        TextFieldPriceOfRoom.setEnabled(false);

        ButtonSaveSeason.setText("Save");
        ButtonSaveSeason.setEnabled(false);
        ButtonSaveSeason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveSeasonActionPerformed(evt);
            }
        });

        DateChooserStartDate.setEnabled(false);

        DateChooserDepartureDate.setEnabled(false);

        jLabel30.setText("Start date ");

        jLabel31.setText("Departure date");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel36))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(ButtonSaveRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TextRoomNumber)
                                    .addComponent(ComboBoxKindOfRoom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextMaxOfPeople)
                                    .addComponent(TextSize)
                                    .addComponent(jScrollPane3)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RadioButtonTerrace)
                                    .addComponent(RadioButtonAllInclude))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RadioButtonSmoke)
                                    .addComponent(RadioButtonSeaView))
                                .addGap(30, 30, 30)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(57, 57, 57)))
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(95, 95, 95))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ButtonSaveService)
                                    .addComponent(ButtonSaveAttractio)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(96, 96, 96))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel24)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextNameService, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(TextCodeAttraction)
                            .addComponent(TextNameAttraction)
                            .addComponent(TextCodeService))
                        .addGap(24, 24, 24)))
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(ButtonSaveSeason)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(31, 31, 31)
                                .addComponent(TextFieldPriceOfRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jButton1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboBoxSeasons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DateChooserDepartureDate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DateChooserStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(TextRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboBoxKindOfRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextMaxOfPeople, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel35))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RadioButtonSeaView)
                                    .addComponent(RadioButtonAllInclude))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RadioButtonSmoke)
                                    .addComponent(RadioButtonTerrace))
                                .addGap(32, 32, 32)
                                .addComponent(ButtonSaveRoom))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(TextCodeAttraction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(TextNameAttraction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(ButtonSaveAttractio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(TextCodeService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextNameService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28))
                                .addGap(28, 28, 28)
                                .addComponent(ButtonSaveService)))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxSeasons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateChooserStartDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel31)
                            .addComponent(DateChooserDepartureDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldPriceOfRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(57, 57, 57)
                        .addComponent(ButtonSaveSeason)
                        .addContainerGap())))
        );

        ButtonExitManage1.setText("Exit");
        ButtonExitManage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExitManage1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxListHotels, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(539, Short.MAX_VALUE))
                    .addComponent(jSeparator7)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(ButtonExitManage1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(ComboBoxListHotels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonExitManage1)
                .addGap(4, 4, 4))
        );

        jTabbedPane1.addTab("Manage a Hotel", jPanel3);

        jLabel1.setText("Hotel name");

        jLabel2.setText("Address ");

        jLabel3.setText("Country");

        jLabel4.setText("Phone number");

        jLabel5.setText("Year of building");

        jLabel6.setText("kind of lodging");

        ComboBoxHotelKindOfLodging.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mountain", "Beach", "City" }));

        jLabel7.setText("Size");

        jLabel8.setText("Hour of Check in");

        jLabel9.setText("Hour of Check out");

        jLabel10.setText("Requirements for check in");

        jScrollPane1.setViewportView(TextPaneHotelRequirementsForCheckIn);

        jLabel11.setText("Stars");

        ComboBoxHotelStars.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        ComboBoxHotelHourOfCheckIn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7 am", "8 am", "9 am" }));

        ComboBoxHotelHourOfCheckOut.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7 pm", "8 pm", "9 pm" }));

        ButtonCreateHotel.setText("Create");
        ButtonCreateHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCreateHotelActionPerformed(evt);
            }
        });

        ButtonExit.setText("Exit");
        ButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextHotelName, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                .addComponent(TextHotelAddress)
                                .addComponent(TextHotelCountry)
                                .addComponent(TextHotelPhoneNumber)
                                .addComponent(TextHotelYearOfBuilding))
                            .addComponent(TextHotelSize, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel6))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ComboBoxHotelHourOfCheckIn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboBoxHotelKindOfLodging, 0, 200, Short.MAX_VALUE)
                                    .addComponent(ComboBoxHotelHourOfCheckOut, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboBoxHotelStars, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonExit)
                        .addGap(483, 483, 483)
                        .addComponent(ButtonCreateHotel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextHotelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(ComboBoxHotelHourOfCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextHotelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ComboBoxHotelHourOfCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextHotelCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(ComboBoxHotelKindOfLodging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(ComboBoxHotelStars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextHotelPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextHotelYearOfBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextHotelSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCreateHotel)
                    .addComponent(ButtonExit))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add Hotel", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonExitManage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExitManage1ActionPerformed
        LogInmMenu logInMenu = new LogInmMenu();
        logInMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonExitManage1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TextRoomNumber.setEnabled(true);
        TextMaxOfPeople.setEnabled(true);
        ComboBoxKindOfRoom.setEnabled(true);
        TextSize.setEnabled(true);
        TextPaneDescription.setEnabled(true);
        RadioButtonAllInclude.setEnabled(true);
        RadioButtonSeaView.setEnabled(true);
        RadioButtonSmoke.setEnabled(true);
        RadioButtonTerrace.setEnabled(true);
        ButtonSaveRoom.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        TextCodeService.setEnabled(true);
        TextNameService.setEnabled(true);
        ButtonSaveService.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TextCodeAttraction.setEnabled(true);
        TextNameAttraction.setEnabled(true);
        ButtonSaveAttractio.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void RadioButtonAllIncludeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadioButtonAllIncludeMouseClicked
        if(RadioButtonAllInclude.isSelected()){

            RadioButtonSeaView.setSelected(true);
            RadioButtonSmoke.setSelected(true);
            RadioButtonTerrace.setSelected(true);
        }else{
            RadioButtonSeaView.setSelected(false);
            RadioButtonSmoke.setSelected(false);
            RadioButtonTerrace.setSelected(false);
        }
    }//GEN-LAST:event_RadioButtonAllIncludeMouseClicked

    private void ButtonSaveServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveServiceActionPerformed
        if(TextCodeService.getText().isEmpty() || TextNameService.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please complete all text fields");
            return;
        }

        String code = TextCodeService.getText().toString();
        String name = TextNameService.getText().toString();

        String hotel = ComboBoxListHotels.getSelectedItem().toString();
        ArrayList<Hotel> hotels = GlobalVariables.getInstance().getAll();
        ArrayList<Service> services = null;
        for (int i = 0; i < hotels.size(); i++) {
            if(hotels.get(i).getName().equals(hotel)) {
                services = hotels.get(i).getServiceList();
                for (int j = 0; j < services.size(); j++) {
                    if(services.get(j).getCode().equals(code)){
                        JOptionPane.showMessageDialog(this, "The service code already exists");
                        return;
                    }
                }
                Service service = new Service(code, name);
                GlobalVariables.getInstance().addServicesToHotel(i, service);
                JOptionPane.showMessageDialog(this, "Service was added");
                break;
            }
        }
        TextCodeService.setEnabled(false);
        TextNameService.setEnabled(false);
        ButtonSaveService.setEnabled(false);
        TextCodeService.setText(null);
        TextNameService.setText(null);

    }//GEN-LAST:event_ButtonSaveServiceActionPerformed

    private void ButtonSaveAttractioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveAttractioActionPerformed

        if(TextCodeAttraction.getText().isEmpty() || TextNameAttraction.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please complete all text fields");
            return;
        }

        String code = TextCodeAttraction.getText().toString();
        String name = TextNameAttraction.getText().toString();

        String hotel = ComboBoxListHotels.getSelectedItem().toString();
        ArrayList<Hotel> hotels = GlobalVariables.getInstance().getAll();
        ArrayList<Attraction> attractions = null;
        for (int i = 0; i < hotels.size(); i++) {
            if(hotels.get(i).getName().equals(hotel)) {
                attractions = hotels.get(i).getAttractionList();
                for (int j = 0; j < attractions.size(); j++) {
                    if(attractions.get(j).getCode().equals(code)){
                        JOptionPane.showMessageDialog(this, "The attraction code already exists");
                        return;
                    }
                }
                Attraction attraction = new Attraction(code, name);
                GlobalVariables.getInstance().addAttractionToHotel(i, attraction);
                JOptionPane.showMessageDialog(this, "Attraction was added");
                break;
            }
        }
        TextCodeAttraction.setEnabled(false);
        TextNameAttraction.setEnabled(false);
        ButtonSaveAttractio.setEnabled(false);
        TextCodeAttraction.setText(null);
        TextNameAttraction.setText(null);

    }//GEN-LAST:event_ButtonSaveAttractioActionPerformed

    private void ButtonSaveRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveRoomActionPerformed

        if(TextRoomNumber.getText().isEmpty() || TextMaxOfPeople.getText().isEmpty()
            || TextSize.getText().isEmpty() ||TextPaneDescription.getText().isEmpty() ){

            JOptionPane.showMessageDialog(this, "Please complete all text fields");
            return;
        }

        int roomNumber = Integer.parseInt(TextRoomNumber.getText());
        String KindOfRoom = ComboBoxKindOfRoom.getSelectedItem().toString();
        int maxPeople = Integer.parseInt(TextMaxOfPeople.getText());
        int size = Integer.parseInt(TextSize.getText());
        String description = TextPaneDescription.getText().toString();
        boolean terrace = false;
        boolean seaView = false;
        boolean smoke = false;
        boolean allIncluded = false;

        if(RadioButtonAllInclude.isSelected()){
            terrace = true;
            seaView = true;
            smoke = true;
            allIncluded = true;
        }else{
            if(RadioButtonSeaView.isSelected()){
                seaView = true;
            }else if(RadioButtonSmoke.isSelected()){
                smoke = true;
            }else if(RadioButtonTerrace.isSelected()){
                terrace = true;
            }
        }

        String hotel = ComboBoxListHotels.getSelectedItem().toString();
        ArrayList<Hotel> hotels = GlobalVariables.getInstance().getAll();
        ArrayList<Room> rooms = null;
        for (int i = 0; i < hotels.size(); i++) {
            if(hotels.get(i).getName().equals(hotel)) {
                rooms = hotels.get(i).getRoomsList();
                for (int j = 0; j < rooms.size(); j++) {
                    if(rooms.get(j).getRoomNumber() == roomNumber){
                        JOptionPane.showMessageDialog(this, "The room number already exists");
                        return;
                    }
                }
                Room room = new Room(roomNumber,new TypeRoom(KindOfRoom,maxPeople,size, description, terrace, seaView, allIncluded,smoke));
                GlobalVariables.getInstance().addRoomToHotel(i, room);
                JOptionPane.showMessageDialog(this, "Room was added");
                break;
            }
        }

        TextRoomNumber.setEnabled(false);
        TextMaxOfPeople.setEnabled(false);
        ComboBoxKindOfRoom.setEnabled(false);
        TextSize.setEnabled(false);
        TextPaneDescription.setEnabled(false);
        RadioButtonAllInclude.setEnabled(false);
        RadioButtonSeaView.setEnabled(false);
        RadioButtonSmoke.setEnabled(false);
        RadioButtonTerrace.setEnabled(false);
        ButtonSaveRoom.setEnabled(false);
        TextRoomNumber.setText(null);
        TextMaxOfPeople.setText(null);
        TextSize.setText(null);
        TextPaneDescription.setText(null);
        RadioButtonAllInclude.setSelected(false);
        RadioButtonSeaView.setSelected(false);
        RadioButtonSmoke.setSelected(false);
        RadioButtonTerrace.setSelected(false);

    }//GEN-LAST:event_ButtonSaveRoomActionPerformed

    private void ButtonLoadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoadDataActionPerformed
        originalName = ComboBoxListHotels1.getSelectedItem().toString();
        ArrayList<Hotel> hotels = GlobalVariables.getInstance().getAll();

        for (int i = 0; i < hotels.size(); i++) {
            if(hotels.get(i).getName().equals(originalName)){

                TextHotelNameManage.setText(hotels.get(i).getName());
                TextHotelAddressManage.setText(hotels.get(i).getAddress());
                TextHotelCountryManage.setText(hotels.get(i).getCountry());
                TextHotelPhoneNumberManage.setText(String.valueOf(hotels.get(i).getPhoneNumber()));
                TextPaneHotelRequirementsForCheckInManage.setText(hotels.get(i).getRequirementsCheckIn());
                TextHotelSizeManage.setText(String.valueOf(hotels.get(i).getSize()));
                TextHotelYearOfBuildingManage.setText(String.valueOf(hotels.get(i).getYearOfBuilding()));

                if(hotels.get(i).getHourCheckIn().equals("7 am")){
                    ComboBoxHotelHourOfCheckInManage.setSelectedIndex(0);
                }else if(hotels.get(i).getHourCheckIn().equals("8 am")){
                    ComboBoxHotelHourOfCheckInManage.setSelectedIndex(1);
                }else{
                    ComboBoxHotelHourOfCheckInManage.setSelectedIndex(2);
                }

                if(hotels.get(i).getHourCheckOut().equals("7 pm")){
                    ComboBoxHotelHourOfCheckOutManage.setSelectedIndex(0);
                }else if(hotels.get(i).getHourCheckOut().equals("8 pm")){
                    ComboBoxHotelHourOfCheckOutManage.setSelectedIndex(1);
                }else{
                    ComboBoxHotelHourOfCheckOutManage.setSelectedIndex(2);
                }

                if(hotels.get(i).getAccommodationType().equals("Mountain")){
                    ComboBoxHotelKindOfLodgingManage.setSelectedIndex(0);
                }else if(hotels.get(i).getAccommodationType().equals("Beach")){
                    ComboBoxHotelKindOfLodgingManage.setSelectedIndex(1);
                }else{
                    ComboBoxHotelKindOfLodgingManage.setSelectedIndex(2);
                }

                ComboBoxHotelStarsManage.setSelectedIndex(hotels.get(i).getNumberStars()-1);
            }
        }
    }//GEN-LAST:event_ButtonLoadDataActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed

        if(JOptionPane.showConfirmDialog(this, "Do you want continue with deleting of '"+ComboBoxListHotels1.getSelectedItem().toString()+"' Hotel") !=0){
            return;
        }
        GlobalVariables.getInstance().deleteHotel(ComboBoxListHotels1.getSelectedItem().toString());
        cleanInfoManage();
        JOptionPane.showMessageDialog(this,"The hotel has been cleared");
        setHotels();
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ButtonSaveManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveManageActionPerformed

        if(TextHotelNameManage.getText().isEmpty() || TextHotelAddressManage.getText().isEmpty()
            || TextHotelCountryManage.getText().isEmpty() ||TextHotelPhoneNumberManage.getText().isEmpty()
            || TextHotelSizeManage.getText().isEmpty() || TextHotelYearOfBuildingManage.getText().isEmpty()){

            JOptionPane.showMessageDialog(this, "Please complete all text fields");
            return;
        }

        String name = TextHotelNameManage.getText();
        String address = TextHotelAddressManage.getText();
        String country = TextHotelCountryManage.getText();
        int phoneNumber = 0;
        int size =0;
        int yearOfBuilding =0;
        try {
            phoneNumber = Integer.parseInt(TextHotelPhoneNumberManage.getText());
            size = Integer.parseInt(TextHotelSizeManage.getText());
            yearOfBuilding = Integer.parseInt(TextHotelYearOfBuildingManage.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Please enter just numbers in Phone Number, size and Year Of Building");
            return;
        }
        int numberStars = Integer.parseInt(ComboBoxHotelStarsManage.getSelectedItem().toString());
        String kindOfLodging = ComboBoxHotelKindOfLodgingManage.getSelectedItem().toString();
        String hourOfCheckIn = ComboBoxHotelHourOfCheckInManage.getSelectedItem().toString();
        String hourOfCheckout  = ComboBoxHotelHourOfCheckOutManage.getSelectedItem().toString();
        String requirements = TextPaneHotelRequirementsForCheckInManage.getText();

        GlobalVariables.getInstance().hotelList.add(new Hotel(name, address, country, phoneNumber, numberStars, kindOfLodging, hourOfCheckIn, hourOfCheckout, requirements, size, yearOfBuilding));
        GlobalVariables.getInstance().deleteHotel(originalName);

        JOptionPane.showMessageDialog(this, "The hotel has been modified");
        cleanInfoManage();
        setHotels();
    }//GEN-LAST:event_ButtonSaveManageActionPerformed

    private void ButtonExitManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExitManageActionPerformed
        LogInmMenu logInMenu = new LogInmMenu();
        logInMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonExitManageActionPerformed

    private void ButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExitActionPerformed
        LogInmMenu logInMenu = new LogInmMenu();
        logInMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonExitActionPerformed

    private void ButtonCreateHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreateHotelActionPerformed

        if(TextHotelName.getText().isEmpty() || TextHotelAddress.getText().isEmpty()
            || TextHotelCountry.getText().isEmpty() ||TextHotelPhoneNumber.getText().isEmpty()
            || TextHotelSize.getText().isEmpty() || TextHotelYearOfBuilding.getText().isEmpty() ){

            JOptionPane.showMessageDialog(this, "Please complete all text fields");
            return;
        }

        String name = TextHotelName.getText();
        String address = TextHotelAddress.getText();
        String country = TextHotelCountry.getText();
        int phoneNumber = 0;
        int size =0;
        int yearOfBuilding =0;
        try {
            phoneNumber = Integer.parseInt(TextHotelPhoneNumber.getText());
            size = Integer.parseInt(TextHotelSize.getText());
            yearOfBuilding = Integer.parseInt(TextHotelYearOfBuilding.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Please enter just numbers in Phone Number, size and Year Of Building");
            return;
        }
        int numberStars = Integer.parseInt(ComboBoxHotelStars.getSelectedItem().toString());
        String kindOfLodging = ComboBoxHotelKindOfLodging.getSelectedItem().toString();
        String hourOfCheckIn = ComboBoxHotelHourOfCheckIn.getSelectedItem().toString();
        String hourOfCheckout  = ComboBoxHotelHourOfCheckOut.getSelectedItem().toString();
        String requirements = TextPaneHotelRequirementsForCheckIn.getText();

        GlobalVariables.getInstance().hotelList.add(new Hotel(name, address, country, phoneNumber, numberStars, kindOfLodging, hourOfCheckIn, hourOfCheckout, requirements, size, yearOfBuilding));
        JOptionPane.showMessageDialog(this, "The hotel has been added");
        cleanInfo();
        setHotels();
    }//GEN-LAST:event_ButtonCreateHotelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ComboBoxSeasons.setEnabled(true);
       ComboBoxRooms.setEnabled(true);
       TextFieldPriceOfRoom.setEnabled(true);
       ButtonSaveSeason.setEnabled(true);
       DateChooserStartDate.setEnabled(true);
       DateChooserDepartureDate.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonSaveSeasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveSeasonActionPerformed
        if(TextFieldPriceOfRoom.getText().toString().isEmpty() || DateChooserDepartureDate.getDate().toString().isEmpty() || DateChooserStartDate.getDate().toString().isEmpty()  ){
            JOptionPane.showMessageDialog(this,"Please complete all text fields");
            return;
        }
        String hotel= ComboBoxListHotels.getSelectedItem().toString();
        String startDate = DateChooserStartDate.getDate().toString();
        String departureDate = DateChooserDepartureDate.getDate().toString();
        String room = ComboBoxRooms.getSelectedItem().toString();
        String season ;
        String codeNewSeason;
        
        if(ComboBoxSeasons.getSelectedIndex() == 0 ){
            season = "High season";
            
            if(ComboBoxRooms.getSelectedIndex() == 0){
                codeNewSeason = "s1";
            }else if(ComboBoxRooms.getSelectedIndex() == 1){
                codeNewSeason = "s2";
            }else{
                codeNewSeason = "s3";
            }

        }else if(ComboBoxSeasons.getSelectedIndex() == 1){
            season = "Low Season";
            if(ComboBoxRooms.getSelectedIndex() == 0){
                codeNewSeason = "d1";
            }else if(ComboBoxRooms.getSelectedIndex() == 1){
                codeNewSeason = "d2";
            }else{
                codeNewSeason = "d3";
            }
        }else{
            season = "Green season";
            if(ComboBoxRooms.getSelectedIndex() == 0){
                codeNewSeason = "i1";
            }else if(ComboBoxRooms.getSelectedIndex() == 1){
                codeNewSeason = "i2";
            }else{
                codeNewSeason = "i3";
            }
        }
        
        
        int price = 0;
        try {
            price = Integer.parseInt(TextFieldPriceOfRoom.getText().toString());
 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter just numbers in 'Price $'");
        }
        
        ArrayList<Hotel> hotels = GlobalVariables.getInstance().getAll();
        ArrayList<Season> seasons = null;
        for (int i = 0; i < hotels.size(); i++) {
            if(hotels.get(i).getName().equals(hotel)) {
                seasons = hotels.get(i).getSeasonList();
                for (int j = 0; j < seasons.size(); j++) {
                    if(seasons.get(j).getCode().equals(codeNewSeason)  && seasons.get(j).getTypeRoom().equals(room)){
                        JOptionPane.showMessageDialog(this, "The season code already exists");
                        return;
                    }
                }
                Season newSeason = new Season(season, codeNewSeason, startDate, departureDate, price, room);
                GlobalVariables.getInstance().addSeasonsToHotel(i, newSeason);
                JOptionPane.showMessageDialog(this, "Season was added");
                break;
            }
        }
        
        
        
       TextFieldPriceOfRoom.setText(null);

    }//GEN-LAST:event_ButtonSaveSeasonActionPerformed
      
    public void setHotels(){
        ComboBoxListHotels.removeAllItems();
        ComboBoxListHotels1.removeAllItems();
        
        ArrayList<Hotel> hotels = GlobalVariables.getInstance().getAll();  
        for (int i = 0; i < hotels.size(); i++) {
            ComboBoxListHotels.addItem(hotels.get(i).getName());
            ComboBoxListHotels1.addItem(hotels.get(i).getName());
      
        }
    }

    
    public void cleanInfo(){
        TextHotelName.setText(null);
        TextHotelAddress.setText(null);
        TextHotelCountry.setText(null);
        TextHotelPhoneNumber.setText(null);
        TextPaneHotelRequirementsForCheckIn.setText(null);
        TextHotelSize.setText(null);
        TextHotelYearOfBuilding.setText(null);
 
    }
    
    public void cleanInfoManage(){
        TextHotelNameManage.setText(null);
        TextHotelAddressManage.setText(null);
        TextHotelCountryManage.setText(null);
        TextHotelPhoneNumberManage.setText(null);
        TextPaneHotelRequirementsForCheckInManage.setText(null);
        TextHotelSizeManage.setText(null);
        TextHotelYearOfBuildingManage.setText(null);
     
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCreateHotel;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonExit;
    private javax.swing.JButton ButtonExitManage;
    private javax.swing.JButton ButtonExitManage1;
    private javax.swing.JButton ButtonLoadData;
    private javax.swing.JButton ButtonSaveAttractio;
    private javax.swing.JButton ButtonSaveManage;
    private javax.swing.JButton ButtonSaveRoom;
    private javax.swing.JButton ButtonSaveSeason;
    private javax.swing.JButton ButtonSaveService;
    private javax.swing.JComboBox ComboBoxHotelHourOfCheckIn;
    private javax.swing.JComboBox ComboBoxHotelHourOfCheckInManage;
    private javax.swing.JComboBox ComboBoxHotelHourOfCheckOut;
    private javax.swing.JComboBox ComboBoxHotelHourOfCheckOutManage;
    private javax.swing.JComboBox ComboBoxHotelKindOfLodging;
    private javax.swing.JComboBox ComboBoxHotelKindOfLodgingManage;
    private javax.swing.JComboBox ComboBoxHotelStars;
    private javax.swing.JComboBox ComboBoxHotelStarsManage;
    private javax.swing.JComboBox ComboBoxKindOfRoom;
    private javax.swing.JComboBox ComboBoxListHotels;
    private javax.swing.JComboBox ComboBoxListHotels1;
    private javax.swing.JComboBox ComboBoxRooms;
    private javax.swing.JComboBox ComboBoxSeasons;
    private com.toedter.calendar.JDateChooser DateChooserDepartureDate;
    private com.toedter.calendar.JDateChooser DateChooserStartDate;
    private javax.swing.JRadioButton RadioButtonAllInclude;
    private javax.swing.JRadioButton RadioButtonSeaView;
    private javax.swing.JRadioButton RadioButtonSmoke;
    private javax.swing.JRadioButton RadioButtonTerrace;
    private javax.swing.JTextField TextCodeAttraction;
    private javax.swing.JTextField TextCodeService;
    private javax.swing.JTextField TextFieldPriceOfRoom;
    private javax.swing.JTextField TextHotelAddress;
    private javax.swing.JTextField TextHotelAddressManage;
    private javax.swing.JTextField TextHotelCountry;
    private javax.swing.JTextField TextHotelCountryManage;
    private javax.swing.JTextField TextHotelName;
    private javax.swing.JTextField TextHotelNameManage;
    private javax.swing.JTextField TextHotelPhoneNumber;
    private javax.swing.JTextField TextHotelPhoneNumberManage;
    private javax.swing.JTextField TextHotelSize;
    private javax.swing.JTextField TextHotelSizeManage;
    private javax.swing.JTextField TextHotelYearOfBuilding;
    private javax.swing.JTextField TextHotelYearOfBuildingManage;
    private javax.swing.JTextField TextMaxOfPeople;
    private javax.swing.JTextField TextNameAttraction;
    private javax.swing.JTextField TextNameService;
    private javax.swing.JTextPane TextPaneDescription;
    private javax.swing.JTextPane TextPaneHotelRequirementsForCheckIn;
    private javax.swing.JTextPane TextPaneHotelRequirementsForCheckInManage;
    private javax.swing.JTextField TextRoomNumber;
    private javax.swing.JTextField TextSize;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
